<?php
/**
 * @file
 * Handles the creation/display of islandora:bornDigitalCModel objects.
 */

 /**
  * Implements hook_islandora_required_objects().
  */
function islandora_born_digital_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_born_digital');
  // Born Digital Content Model.
  $born_digital_model = $connection->repository->constructObject('islandora:bornDigitalCModel');
  $born_digital_model->owner = 'fedoraAdmin';
  $born_digital_model->label = 'Islandora Born Digital Content Model';
  $born_digital_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM Datastream.
  $datastream = $born_digital_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_born_digital_content_model.xml", FALSE);
  $born_digital_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $born_digital_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_born_digital_ds_composite_model.xml", FALSE);
  $born_digital_model->ingestDatastream($datastream);
  // Born Digital Collection.
  $born_digital_collection = $connection->repository->constructObject('islandora:born_digital_collection');
  $born_digital_collection->owner = 'fedoraAdmin';
  $born_digital_collection->label = 'Born Digital Collection';
  $born_digital_collection->models = 'islandora:collectionCModel';
  $born_digital_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $born_digital_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_born_digital_collection_policy.xml", FALSE);
  $born_digital_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $born_digital_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $born_digital_collection->ingestDatastream($datastream);
  return array(
    'islandora_born_digital' => array(
      'title' => 'Islandora born digital',
      'objects' => array(
        $born_digital_model,
        $born_digital_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_born_digital_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_born_digital');
  return array(
    'Born Digital MODS form' => array(
      'form_file' => "$module_path/xml/islandora_born_digital_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_born_digital_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_born_digital_mods_form' => array(
      'content_model' => 'islandora:bornDigitalCModel',
      'form_name' => 'Born Digital MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_born_digital_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_born_digital' => array(
      'template' => 'theme/islandora-born-digital',
      'pattern' => 'islandora_born_digital__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_born_digital_islandora_bornDigitalCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_born_digital', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_born_digital_islandora_bornDigitalCModel_islandora_ingest_steps() {
  return array(
    'islandora_tei_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_born_digital_tei_upload_form',
      'module' => 'islandora_born_digital',
      'file' => 'includes/tei_upload.form.inc',
    ),
  );
}
